server:
  tomcat:
    max-swallow-size: 2024MB
  port: 8080
  shutdown: graceful
  address: 192.168.0.6

spring:

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: root
    password: ${DB_PASSWORD}
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_DATABASE:test}
    sql:
      init:
        mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  accessSecret: KhheB0euerVivwCL7P1WA0CL/N8Dt6EyQEa/Wi1XLaY5beneRnADC4KUQ+PAxMUBk8JuJvFl9mWk7zfkoNWlmA==
  refreshSecret: RGNVNSDJAdDVhbGRvb2HzJEAjIQ==Wi1XLaY5beneRnADC4KUQ+PAxMUBk8J
cloud:
  aws:
    stack:
      auto: false
    s3:
      bucket: mitalk-s3
      url: https://mitalk-s3.s3.ap-northeast-2.amazonaws.com/
    region:
      static: ap-northeast-2
      auto: false
    credentials:
      access-Key: AKIAVQO2VDIU27MZ5W6A
      secret-Key: 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
