server:
  port: 8080
  shutdown: graceful

spring:
  datasource:
    driver-class-name:
  redis:
    host: localhost
    port: 6379

  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_DATABASE:test}
  sql:
    init:
      mode: always