server:
  tomcat:
    max-swallow-size: 2024MB
  shutdown: graceful

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: root
    password: ${DB_PASSWORD:test1234}
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_DATABASE:test}
    sql:
      init:
        mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
jwt:
  accessSecret: ${JWT_ACCESS_SECRET}
  refreshSecret: ${JWT_REFRESH_SECRET}
cloud:
  aws:
    stack:
      auto: false
    s3:
      bucket: mitalk-s3
      url: ${AWS_URL}
    region:
      static: ap-northeast-2
      auto: false
    credentials:
      access-Key: ${AWS_ACCESS_KEY}
      secret-Key: ${AWS_SECRET_KEY}

