spring:
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/practice?serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${DB_USER:cos}
    password: ${DB_PWD:cos1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
