spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true